#!/usr/bin/env bash
# deploy.sh - Build and deploy all AgentTrust contracts to Stellar testnet.
set -euo pipefail

# ── Colors ──────────────────────────────────────────────────────────────────
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
BLUE='\033[0;34m'
CYAN='\033[0;36m'
NC='\033[0m' # No Color

# ── Helpers ─────────────────────────────────────────────────────────────────
info()    { printf "${BLUE}[INFO]${NC}  %s\n" "$*"; }
success() { printf "${GREEN}[OK]${NC}    %s\n" "$*"; }
warn()    { printf "${YELLOW}[WARN]${NC}  %s\n" "$*"; }
fail()    { printf "${RED}[FAIL]${NC}  %s\n" "$*"; exit 1; }

# ── Configuration ───────────────────────────────────────────────────────────
PROJECT_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
NETWORK="testnet"
WASM_TARGET="wasm32v1-none"
WASM_DIR="${PROJECT_ROOT}/target/${WASM_TARGET}/release"
ENV_FILE="${PROJECT_ROOT}/.env"

CONTRACTS=(
    "agent-registry"
    "reputation-engine"
    "stake-manager"
    "dispute-handler"
    "x402-verifier"
)

# ── Step 1: Check prerequisites ─────────────────────────────────────────────
printf "\n${CYAN}═══════════════════════════════════════════════════════${NC}\n"
printf "${CYAN}  AgentTrust Contract Deployment${NC}\n"
printf "${CYAN}═══════════════════════════════════════════════════════${NC}\n\n"

info "Checking prerequisites..."

if ! command -v stellar &> /dev/null && ! command -v soroban &> /dev/null; then
    fail "Neither 'stellar' nor 'soroban' CLI found. Install with: cargo install stellar-cli"
fi

# Determine which CLI binary to use
if command -v stellar &> /dev/null; then
    CLI="stellar"
else
    CLI="soroban"
fi
success "Found CLI: ${CLI} ($(${CLI} --version 2>/dev/null || echo 'unknown version'))"

if ! command -v cargo &> /dev/null; then
    fail "'cargo' not found. Install Rust: https://rustup.rs"
fi
success "Found cargo: $(cargo --version)"

# Check for the Soroban-compatible WASM target
if ! rustup target list --installed 2>/dev/null | grep -q "^${WASM_TARGET}$"; then
    warn "${WASM_TARGET} target not installed. Installing..."
    rustup target add "${WASM_TARGET}"
    success "Installed ${WASM_TARGET} target"
else
    success "${WASM_TARGET} target available"
fi

# ── Step 2: Build all contracts ──────────────────────────────────────────────
printf "\n${CYAN}── Building Contracts ──────────────────────────────────${NC}\n\n"

cd "${PROJECT_ROOT}"

for contract in "${CONTRACTS[@]}"; do
    info "Building ${contract}..."
    cargo build \
        --release \
        --target "${WASM_TARGET}" \
        --package "${contract}" \
        2>&1 | tail -1 || fail "Failed to build ${contract}"

    # Convert kebab-case to snake_case for the WASM filename
    wasm_name="${contract//-/_}"
    wasm_file="${WASM_DIR}/${wasm_name}.wasm"

    if [ ! -f "${wasm_file}" ]; then
        fail "Expected WASM file not found: ${wasm_file}"
    fi

    wasm_size=$(du -h "${wasm_file}" | cut -f1)
    success "Built ${contract} (${wasm_size})"
done

# ── Step 3: Deploy contracts to testnet ──────────────────────────────────────
printf "\n${CYAN}── Deploying to ${NETWORK} ─────────────────────────────────${NC}\n\n"

declare -A CONTRACT_IDS

for contract in "${CONTRACTS[@]}"; do
    info "Deploying ${contract}..."

    wasm_name="${contract//-/_}"
    wasm_file="${WASM_DIR}/${wasm_name}.wasm"

    contract_id=$(${CLI} contract deploy \
        --wasm "${wasm_file}" \
        --network "${NETWORK}" \
        2>&1) || fail "Failed to deploy ${contract}: ${contract_id}"

    CONTRACT_IDS["${contract}"]="${contract_id}"
    success "Deployed ${contract}: ${contract_id}"
done

# ── Step 4: Write contract IDs to .env ───────────────────────────────────────
printf "\n${CYAN}── Writing .env ────────────────────────────────────────${NC}\n\n"

# Back up existing .env if present
if [ -f "${ENV_FILE}" ]; then
    cp "${ENV_FILE}" "${ENV_FILE}.bak"
    info "Backed up existing .env to .env.bak"
fi

cat > "${ENV_FILE}" << EOF
# AgentTrust Contract Configuration
# Generated by deploy.sh on $(date -u '+%Y-%m-%d %H:%M:%S UTC')

SOROBAN_RPC_URL=https://soroban-testnet.stellar.org
SOROBAN_NETWORK_PASSPHRASE=Test SDF Network ; September 2015
STELLAR_NETWORK=${NETWORK}

# Contract IDs
AGENT_REGISTRY_CONTRACT_ID=${CONTRACT_IDS["agent-registry"]}
REPUTATION_ENGINE_CONTRACT_ID=${CONTRACT_IDS["reputation-engine"]}
STAKE_MANAGER_CONTRACT_ID=${CONTRACT_IDS["stake-manager"]}
DISPUTE_HANDLER_CONTRACT_ID=${CONTRACT_IDS["dispute-handler"]}
X402_VERIFIER_CONTRACT_ID=${CONTRACT_IDS["x402-verifier"]}

# Frontend
NEXT_PUBLIC_NETWORK=${NETWORK}
NEXT_PUBLIC_RPC_URL=https://soroban-testnet.stellar.org
NEXT_PUBLIC_AGENT_REGISTRY_CONTRACT_ID=${CONTRACT_IDS["agent-registry"]}
NEXT_PUBLIC_REPUTATION_ENGINE_CONTRACT_ID=${CONTRACT_IDS["reputation-engine"]}
NEXT_PUBLIC_STAKE_MANAGER_CONTRACT_ID=${CONTRACT_IDS["stake-manager"]}
NEXT_PUBLIC_DISPUTE_HANDLER_CONTRACT_ID=${CONTRACT_IDS["dispute-handler"]}
NEXT_PUBLIC_X402_VERIFIER_CONTRACT_ID=${CONTRACT_IDS["x402-verifier"]}

# Launchtube (fill in manually)
NEXT_PUBLIC_LAUNCHTUBE_URL=https://launchtube.xyz
LAUNCHTUBE_URL=
LAUNCHTUBE_JWT=
EOF

success "Wrote contract IDs to ${ENV_FILE}"

# ── Summary ──────────────────────────────────────────────────────────────────
printf "\n${CYAN}═══════════════════════════════════════════════════════${NC}\n"
printf "${GREEN}  Deployment Complete${NC}\n"
printf "${CYAN}═══════════════════════════════════════════════════════${NC}\n\n"

printf "%-22s %s\n" "Contract" "Contract ID"
printf "%-22s %s\n" "────────────────────" "────────────────────────────────────────────────────"
for contract in "${CONTRACTS[@]}"; do
    printf "%-22s %s\n" "${contract}" "${CONTRACT_IDS[${contract}]}"
done

printf "\n"
info "Next steps:"
info "  1. Run ./scripts/initialize.sh to initialize all contracts"
info "  2. Run ./scripts/seed-testnet.sh to create sample agents"
printf "\n"
